version: '3'
services:
    web:
        logging:
          options:
            max-size: 10m
        image: nginx:alpine
        volumes:
            - "./.docker/etc/nginx/default.conf:/etc/nginx/conf.d/default.conf"
            - "./.docker/etc/ssl:/etc/ssl"
            - "./.docker/etc/nginx/default.template.conf:/etc/nginx/conf.d/default.template"
            - "./:/var/www"
        ports:
            - "10080:80"
            - "10443:443"
            - "10444:444"
        environment:
            - NGINX_HOST=${NGINX_HOST}
        command: /bin/sh -c "envsubst '$$NGINX_HOST' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
        restart: unless-stopped
        healthcheck:
          test: ["CMD-SHELL", "wget --quiet --tries=1 --spider http://localhost/ || exit 1"]
          interval: 1m
          timeout: 10s
          retries: 3
        depends_on:
            - fpm
    fpm:
        logging:
          options:
            max-size: 10m
        build: ./.docker
        restart: unless-stopped
        environment:
            - MICROSERVICE_APIKEY=${MICROSERVICE_APIKEY}
        volumes:
            - "./.docker/etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
            - "./.docker/etc/php/php-fpm.ini:/usr/local/etc/php-fpm.d/www.conf"
            - "./:/var/www"
    composer:
        logging:
          options:
            max-size: 10m
        restart: 'no'
        image: composer/composer:php7
        command: install
        volumes:
        - .:/app